### ISSUE TITLE
Plans to eventually get this back into mainline?

### ISSUE THREAD

**Issue by meganukebmp** [shadow578/Marlin-H32#31]
Great work on this so far! I'm glad someone is putting in the work needed (I tried and failed myself).
Maybe a bit too early to ask, but do you plan on contributing this back into mainline Marlin when you feel its mature enough? This would be a fantastic contribution (and possibly pulling in more maintainers as a result)

Thanks for the fantastic work here.

**Comment by classicrocker883** [comment]
I'd like to say it is nearly there. I have used this in my own fork and had success, however some minor changes I had to make.

using this on the Aquila with this chip definitely works, but the next step I say is getting it to work with the 12864 lcd like on the Aquila C2.

**Comment by shadow578** [comment]
@meganukebmp i'd really like to get this back into mainline Marlin at some point, for one because it'd pull more mainainers in, but also because it's kinda cumbersome to merge their changes all the time. 

The more maintainers one is especially important to me because i, for one, don't have any way of actually debugging the code. I have to flash the firmware onto my (only) printer and hope for the best. 
Also, since my lectures started a few months ago, progress has very noticeably slowed down. 

I'm currently working on updating the DDL (the sdk for the HC32F460) to the latest (and most importantly official) version.

After that, i could look into creating a PR. Tho i'm not quite sure how to do that the best way.

**Comment by shadow578** [comment]
opened PR https://github.com/MarlinFirmware/Marlin/pull/26414 on upstream repo just now

**Comment by classicrocker883** [comment]
is everything running right so far? I heard someone else using this had an issue with auto bed leveling, I think it was restarting trying to save the mesh. are there any other issues or is everything else good to go?

**Comment by shadow578** [comment]
@classicrocker883 on my machine everything is working fine, as part of https://github.com/shadow578/Marlin-H32/pull/53 i've conducted some longer running stability tests (all using bilininar ABL w/ BLTouch). 
Since then, i've actually printed a bit more, all without issues
